# Generated by Django 5.2.6 on 2025-09-13 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shape_type', models.CharField(choices=[('rectangle', 'Rectangle'), ('circle', 'Circle'), ('polygon', 'Polygon'), ('point', 'Point')], default='rectangle', max_length=20)),
                ('coordinates', models.JSONField(help_text='JSON array of coordinate points')),
                ('label', models.CharField(help_text='Annotation label/description', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
