# Generated by Django 5.2.6 on 2025-09-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Image title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Image description')),
                ('image_url', models.URLField(help_text='URL to the high-resolution image')),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL to thumbnail image')),
                ('source', models.CharField(default='NASA', help_text='Image source', max_length=100)),
                ('category', models.CharField(blank=True, help_text='Image category', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
